- name: Change Port Range
  sysctl: 
    name: net.ipv4.ip_local_port_range
    value: '1024 65000'
    sysctl_set: yes
    state: present

- name: Change Kernal Parameter, Enabled Forward
  sysctl: 
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present

- name: Enabled tcp_reuse
  sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: '1'
    sysctl_set: yes 
    state: present

- name: Change tcp_tw_buckets
  sysctl:
    name: net.ipv4.tcp_max_tw_buckets
    value: '5000'
    sysctl_set: yes
    state: present

- name: Change tcp_syncookies
  sysctl:
    name: net.ipv4.tcp_syncookies
    value: '1'
    sysctl_set: yes
    state: present

- name: Change tcp max_syn_backlog
  sysctl:
    name: net.ipv4.tcp_max_tw_buckets
    value: '8192'
    sysctl_set: yes
    state: present

- name: Change tcp Established Maxconn
  sysctl:
    name: net.core.somaxconn
    value: '32768'
    sysctl_set: yes
    state: present

- name: Change tcp_syn_retries
  sysctl:
    name: net.ipv4.tcp_syn_retries
    value: '2'
    sysctl_set: yes
    state: present    

- name: Change tcp_synack_retries
  sysctl:
    name: net.ipv4.tcp_synack_retries
    value: '2'
    sysctl_set: yes
    state: present    