- name: Installed Packages All
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - rsync
    - nfs-utils
    - net-tools
    - wget
    - tree
    - lrzsz
    - vim
    - unzip
    - httpd-tools
    - bash-completion
    - iftop
    - iotop
    - glances
    - gzip
    - psmisc
    - MySQL-python