- hosts: webservers
  tasks:
    - name: String
      shell: echo $RANDOM | md5sum | cut -c 2-10
      register: systemd_sj

    - name: debug
      debug: 
        msg: "{{ systemd_sj.stdout }}"

    - name: Change Hostname
      hostname:
        name: "web_{{ systemd_sj.stdout }}"


#Use facts to get Server infoes.
- hosts: webservers
  tasks:

    - name: Print IP
      debug:
        msg: "{{ ansible_eth1.ipv4.address }} {{ ansible_fqdn }} {{ ansible_processor_vcpus }} "