apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: app
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
      - name: app-container
        image: oldxu3957/demoapp:v1
        ports:
        - containerPort: 80
        
